/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.cyberbotics.webots.controller;

public class Connector extends Device {
  private transient long swigCPtr;

  protected Connector(long cPtr, boolean cMemoryOwn) {
    super(wrapperJNI.Connector_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Connector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(Connector obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        wrapperJNI.delete_Connector(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public Connector(String name) {
    this(wrapperJNI.new_Connector__SWIG_0(name), true);
  }

  public Connector(int tag) {
    this(wrapperJNI.new_Connector__SWIG_1(tag), true);
  }

  public void enablePresence(int samplingPeriod) {
    wrapperJNI.Connector_enablePresence(swigCPtr, this, samplingPeriod);
  }

  public void disablePresence() {
    wrapperJNI.Connector_disablePresence(swigCPtr, this);
  }

  public int getPresenceSamplingPeriod() {
    return wrapperJNI.Connector_getPresenceSamplingPeriod(swigCPtr, this);
  }

  public int getPresence() {
    return wrapperJNI.Connector_getPresence(swigCPtr, this);
  }

  public boolean isLocked() {
    return wrapperJNI.Connector_isLocked(swigCPtr, this);
  }

  public void lock() {
    wrapperJNI.Connector_lock(swigCPtr, this);
  }

  public void unlock() {
    wrapperJNI.Connector_unlock(swigCPtr, this);
  }

}
