/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.cyberbotics.webots.controller;

public class Motion {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Motion(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Motion obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(Motion obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        wrapperJNI.delete_Motion(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Motion(String fileName) {
    this(wrapperJNI.new_Motion(fileName), true);
  }

  public boolean isValid() {
    return wrapperJNI.Motion_isValid(swigCPtr, this);
  }

  public void play() {
    wrapperJNI.Motion_play(swigCPtr, this);
  }

  public void stop() {
    wrapperJNI.Motion_stop(swigCPtr, this);
  }

  public int getDuration() {
    return wrapperJNI.Motion_getDuration(swigCPtr, this);
  }

  public int getTime() {
    return wrapperJNI.Motion_getTime(swigCPtr, this);
  }

  public void setTime(int time) {
    wrapperJNI.Motion_setTime(swigCPtr, this, time);
  }

  public void setReverse(boolean reverse) {
    wrapperJNI.Motion_setReverse(swigCPtr, this, reverse);
  }

  public void setLoop(boolean loop) {
    wrapperJNI.Motion_setLoop(swigCPtr, this, loop);
  }

  public boolean isOver() {
    return wrapperJNI.Motion_isOver(swigCPtr, this);
  }

}
