/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.cyberbotics.webots.controller;

public class Pen extends Device {
  private transient long swigCPtr;

  protected Pen(long cPtr, boolean cMemoryOwn) {
    super(wrapperJNI.Pen_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Pen obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(Pen obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        wrapperJNI.delete_Pen(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public Pen(String name) {
    this(wrapperJNI.new_Pen__SWIG_0(name), true);
  }

  public Pen(int tag) {
    this(wrapperJNI.new_Pen__SWIG_1(tag), true);
  }

  public void write(boolean write) {
    wrapperJNI.Pen_write(swigCPtr, this, write);
  }

  public void setInkColor(int color, double density) {
    wrapperJNI.Pen_setInkColor(swigCPtr, this, color, density);
  }

}
