/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.cyberbotics.webots.controller;

public class Proto {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Proto(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Proto obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(Proto obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        throw new UnsupportedOperationException("C++ destructor does not have public access");
      }
      swigCPtr = 0;
    }
  }

// ----- begin hand written section ----
  public Proto getParent() {
    long cPtr = wrapperJNI.Proto_getParentPrivate(swigCPtr, this);
    return Proto.findProto(cPtr);
  }

  public Field getField(String fieldName) {
    long cPtr = wrapperJNI.Proto_getFieldPrivate(swigCPtr, this, fieldName);
    return Field.findField(cPtr);
  }

  public Field getFieldByIndex(int index) {
    long cPtr = wrapperJNI.Proto_getFieldByIndexPrivate(swigCPtr, this, index);
    return Field.findField(cPtr);
  }

  private static java.util.HashMap<Long,Proto> protos = new java.util.HashMap<Long,Proto>();

  // DO NOT USE THIS FUNCTION: IT IS RESERVED FOR INTERNAL USE !
  public static Proto findProto(long cPtr) {
    if (cPtr == 0)
      return null;

    Proto proto = protos.get(new Long(cPtr));
    if (proto != null)
      return proto;

    proto = new Proto(cPtr, false);
    protos.put(new Long(cPtr), proto);
    return proto;
  }

  public String getTypeName() {
    return wrapperJNI.Proto_getTypeName(swigCPtr, this);
  }

  public boolean isDerived() {
    return wrapperJNI.Proto_isDerived(swigCPtr, this);
  }

  private Proto getParentPrivate() {
    long cPtr = wrapperJNI.Proto_getParentPrivate(swigCPtr, this);
    return (cPtr == 0) ? null : new Proto(cPtr, false);
  }

  private Field getFieldPrivate(String fieldName) {
    long cPtr = wrapperJNI.Proto_getFieldPrivate(swigCPtr, this, fieldName);
    return (cPtr == 0) ? null : new Field(cPtr, false);
  }

  private Field getFieldByIndexPrivate(int index) {
    long cPtr = wrapperJNI.Proto_getFieldByIndexPrivate(swigCPtr, this, index);
    return (cPtr == 0) ? null : new Field(cPtr, false);
  }

  public int getNumberOfFields() {
    return wrapperJNI.Proto_getNumberOfFields(swigCPtr, this);
  }

}
