/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.cyberbotics.webots.controller;

public class RangeFinder extends Device {
  private transient long swigCPtr;

  protected RangeFinder(long cPtr, boolean cMemoryOwn) {
    super(wrapperJNI.RangeFinder_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(RangeFinder obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(RangeFinder obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        wrapperJNI.delete_RangeFinder(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public RangeFinder(String name) {
    this(wrapperJNI.new_RangeFinder__SWIG_0(name), true);
  }

  public RangeFinder(int tag) {
    this(wrapperJNI.new_RangeFinder__SWIG_1(tag), true);
  }

  public void enable(int samplingPeriod) {
    wrapperJNI.RangeFinder_enable(swigCPtr, this, samplingPeriod);
  }

  public void disable() {
    wrapperJNI.RangeFinder_disable(swigCPtr, this);
  }

  public int getSamplingPeriod() {
    return wrapperJNI.RangeFinder_getSamplingPeriod(swigCPtr, this);
  }

  public float[] getRangeImage() {
    return wrapperJNI.RangeFinder_getRangeImage(swigCPtr, this);
  }

  public int getWidth() {
    return wrapperJNI.RangeFinder_getWidth(swigCPtr, this);
  }

  public int getHeight() {
    return wrapperJNI.RangeFinder_getHeight(swigCPtr, this);
  }

  public double getFov() {
    return wrapperJNI.RangeFinder_getFov(swigCPtr, this);
  }

  public double getMinRange() {
    return wrapperJNI.RangeFinder_getMinRange(swigCPtr, this);
  }

  public double getMaxRange() {
    return wrapperJNI.RangeFinder_getMaxRange(swigCPtr, this);
  }

  public int saveImage(String filename, int quality) {
    return wrapperJNI.RangeFinder_saveImage(swigCPtr, this, filename, quality);
  }

  public static float rangeImageGetDepth(float[] image, int width, int x, int y) {
    return wrapperJNI.RangeFinder_rangeImageGetDepth(image, width, x, y);
  }

}
