/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.cyberbotics.webots.controller;

public class SWIGTYPE_p_WbImageStructPrivate {
  private transient long swigCPtr;

  protected SWIGTYPE_p_WbImageStructPrivate(long cPtr, @SuppressWarnings("unused") boolean futureUse) {
    swigCPtr = cPtr;
  }

  protected SWIGTYPE_p_WbImageStructPrivate() {
    swigCPtr = 0;
  }

  protected static long getCPtr(SWIGTYPE_p_WbImageStructPrivate obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(SWIGTYPE_p_WbImageStructPrivate obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }
}

