/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.cyberbotics.webots.controller;

public interface wrapperConstants {
  public final static int WB_ANGULAR = 0;
  // WbJointType 
  public final static int WB_ROTATIONAL = 0;
  public final static int WB_LINEAR = WB_ROTATIONAL + 1;

}
